import {CARS,TRACKS,WEATHER} from './data.js';
export const DEFAULTS={car:'f296',track:'lemans',session:'race',length:20,unit:'minutes',weather:'dry',air:20,trackTemp:30,grip:'normal',balance:'balanced',rules:'open',lapTime:'',consumption:'',tank:'',startFuel:'',reserve:1,formation:.5,timedExtra:1,flyingLaps:2,outLaps:1,inLaps:0,mandatoryStops:0,vePerLap:'',veStart:100,veReserve:2,tyreAge:'fresh',tyreCompound:'auto',variant:'Current in-game version',wind:'calm',baseWet:false,refuelRate:'',pitLoss:45,customClass:'LMGT3',customKm:5,customName:'My car',customTrack:'My circuit',customAero:'medium',customBumps:1};
const num=(v,f,min=0,max=1e9)=>v===''||v==null?f:Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
const integer=(v,f,min,max)=>Math.floor(num(v,f,min,max));
export const ceilTenth=n=>Math.ceil((n-1e-8)*10)/10;
export function parseLap(v){if(typeof v==='number')return Number.isFinite(v)&&v>0?v:null;const t=String(v||'').trim();if(/^\d+(?:\.\d+)?$/.test(t))return Number(t)>0?Number(t):null;const m=t.match(/^(\d+):([0-5]?\d(?:\.\d+)?)$/);return m&&Number(m[1])*60+Number(m[2])>0?Number(m[1])*60+Number(m[2]):null;}
export const formatLap=s=>{const n=Math.round(s*10)/10;return `${Math.floor(n/60)}:${(n%60).toFixed(1).padStart(4,'0')}`;};
export function normalise(input={}){const s={...DEFAULTS};if(input&&typeof input==='object')for(const k of Object.keys(DEFAULTS))if(Object.hasOwn(input,k)&&['string','number','boolean'].includes(typeof input[k]))s[k]=input[k];if(!CARS.some(c=>c.id===s.car))s.car=DEFAULTS.car;if(!TRACKS.some(t=>t.id===s.track))s.track=DEFAULTS.track;if(!['race','quali','practice'].includes(s.session))s.session='race';if(!['minutes','hours','laps','km'].includes(s.unit))s.unit='minutes';if(!WEATHER.some(w=>w[0]===s.weather))s.weather='dry';s.length=num(s.length,20,.1,100000);s.baseWet=s.baseWet===true||s.baseWet==='true';return s;}
export function context(input){const s=normalise(input);let car={...CARS.find(c=>c.id===s.car)},track={...TRACKS.find(t=>t.id===s.track)};if(car.id==='custom'){const cls=['LMGT3','GTE','LMP2','LMP3','Hypercar'].includes(s.customClass)?s.customClass:'LMGT3';car={...car,name:String(s.customName||'My car'),cls,abs:cls==='LMGT3',ve:['LMGT3','Hypercar'].includes(cls)};}if(track.id==='custom')track={...track,circuit:String(s.customTrack||'My circuit'),km:num(s.customKm,5,.2,50),aero:['low','medium','high'].includes(s.customAero)?s.customAero:'medium',bumps:integer(s.customBumps,1,1,3)};return{s,car,track};}
export function fuelPlan(input){const {s,car,track}=context(input),wetFactor={dry:1,damp:1.07,wet:1.17,heavy:1.3,drying:1.1,worsening:1.13}[s.weather];
 const pace={LMGT3:170,GTE:180,Hypercar:205,LMP2:198,LMP3:176}[car.cls],speed=pace*(track.aero==='low'?1.13:track.aero==='high'?.9:1);
 const measuredLap=parseLap(s.lapTime),lap=measuredLap||Math.max(25,track.km/speed*3600*wetFactor),measuredConsumption=num(s.consumption,null,.01,100),consumption=measuredConsumption||track.km*({LMGT3:.40,GTE:.44,Hypercar:.43,LMP2:.45,LMP3:.34}[car.cls]);
 const seconds=s.unit==='hours'?s.length*3600:s.unit==='minutes'?s.length*60:null;
 let laps,extras=0;if(s.session==='quali'){laps=s.unit==='laps'?Math.ceil(s.length):s.unit==='km'?Math.ceil(s.length/track.km):integer(s.flyingLaps,2,1,50);extras=integer(s.outLaps,1,0,10)+integer(s.inLaps,0,0,10);}else{laps=s.unit==='laps'?Math.ceil(s.length):s.unit==='km'?Math.ceil(s.length/track.km):Math.max(1,Math.ceil(seconds/lap));if(s.session==='race'&&seconds)laps+=integer(s.timedExtra,1,0,5);extras=s.session==='race'?num(s.formation,.5,0,5):integer(s.outLaps,1,0,10);}
 const reserve=num(s.reserve,1,0,10),totalFuel=ceilTenth((laps+extras+reserve)*consumption),tank=num(s.tank,null,.1,500),manual=num(s.startFuel,null,.1,500),reserveL=reserve*consumption,warnings=[];
 if(!measuredLap||!measuredConsumption)warnings.push('Provisional estimate: add your measured lap time and litres per lap before relying on this fuel plan.');
 if(!tank)warnings.push('Enter the tank capacity shown in your garage to calculate stops. No capacity is assumed.');
 if(s.session==='quali'&&seconds&&(laps+extras)*lap>seconds)warnings.push('This qualifying run may not fit the session clock. Reduce flying laps or check the event’s finish rules.');
 if(manual&&tank&&manual>tank)warnings.push('Requested starting fuel exceeds the entered tank capacity. The plan caps it at that capacity.');
 const startFuel=Math.min(manual??totalFuel,tank??Infinity),veUse=car.ve?num(s.vePerLap,null,.01,100):null,veReserve=car.ve?num(s.veReserve,2,0,50):0,veLaps=veUse?Math.max(0,Math.floor((num(s.veStart,100,1,100)-veReserve)/veUse)):null;
 const maxStint=tank?Math.floor((tank-reserveL)/consumption):null,stints=[];let stops=null,complete=false;
 if(tank){let remaining=laps,position=0,maxFull=maxStint;if(veUse)maxFull=Math.min(maxFull,Math.floor((100-veReserve)/veUse));let firstCap=Math.floor((startFuel-reserveL-extras*consumption+1e-8)/consumption);if(veLaps!==null)firstCap=Math.min(firstCap,veLaps);
  if(firstCap<1||maxFull<1)warnings.push('The fuel or virtual energy is insufficient for one lap with these reserves. Increase the load or review the reserve.');
  else{const minimum=s.session==='race'?integer(s.mandatoryStops,0,0,20):0;while(remaining>0&&stints.length<200){const first=stints.length===0,cap=first?firstCap:maxFull,legs=Math.max(1,minimum+1-stints.length),run=Math.min(cap,remaining,Math.ceil(remaining/legs));stints.push({number:stints.length+1,start:position+1,end:position+run,laps:run,minutes:run*lap/60,fuel:ceilTenth((run+reserve+(first?extras:0))*consumption),ve:veUse?ceilTenth(run*veUse+veReserve):null});position+=run;remaining-=run;}stops=Math.max(0,stints.length-1);complete=remaining===0;if(!complete)warnings.push('Schedule truncated at 200 stints; shorten the session for a complete plan.');if(stops<minimum)warnings.push('Too few racing laps for the requested mandatory stops.');}
 }
 if(manual&&manual<totalFuel&&!tank)warnings.push('The starting load is below session fuel. Enter tank capacity to plan refuelling.');
 if(car.ve&&!veUse)warnings.push('Virtual energy is not yet included. Enter the measured percentage used per racing lap to check stint limits.');
 if(s.session==='race'&&seconds)warnings.push('Timed distance includes the extra-lap allowance. Class leader pace, traffic and the finish rules can change the actual lap count.');
 return{lap,consumption,measured:!!(measuredLap&&measuredConsumption),measuredLap:!!measuredLap,measuredConsumption:!!measuredConsumption,laps,extras,reserve,totalFuel,startFuel:ceilTenth(startFuel),tank,maxStint,veLaps,veUse,stints,stops,complete,warnings,seconds,minutes:(laps+extras)*lap/60,pitLoss:stops===null?null:stops*num(s.pitLoss,45,0,600),refuelRate:num(s.refuelRate,null,.01,50)};
}
export function buildSetup(input){const {s,car,track}=context(input),f=fuelPlan(s),wet=['wet','heavy','worsening'].includes(s.weather),wb=wet&&s.baseWet,stable=s.balance==='stable',proto=['Hypercar','LMP2','LMP3'].includes(car.cls),rows=[];
 const add=(id,group,name,value,why,trade,test,changed=false,conditional=false)=>rows.push({id,group,name,value,why,trade,test,changed,conditional,status:'Starting guidance'});
 const wing=car.wingless?'No conventional rear wing':wet?(wb?'Keep wet baseline':`Test ${s.weather==='heavy'?2:1} step${s.weather==='heavy'?'s':''} more wing`):s.session==='quali'&&track.aero==='low'&&!stable?'Test 1 step less wing':'Keep track baseline';
 add('wing','Aero & platform','Rear wing',wing,car.wingless?'The original 9X8 uses a different aero platform.':wet?'Extra rear aero can help confidence in low grip.':track.aero==='low'?'Straight-line efficiency matters here. Compare the entire lap.':'Start with the game’s baseline for this circuit.','More wing costs top speed; less wing costs rear grip.','Compare high-speed confidence and lap time at equal fuel.',!car.wingless&&!wing.startsWith('Keep'));
 add('frontaero','Aero & platform','Front aero / dive planes','Keep track baseline','Preserve aero balance while you evaluate the rear wing.','More front aero can loosen the rear.','Use only controls actually exposed by this car.',false,true);
 for(const axle of ['Front','Rear'])add(axle==='Front'?'frontheight':'rearheight','Aero & platform',`${axle} ride height`,wet&&!wb?'Test 1 step higher, both axles':'Keep track baseline',wet?'More clearance may help on standing water. Keep rake unchanged initially.':proto?'Prototype aero is sensitive to platform changes.':'Check loaded clearance before lowering.','Height changes affect both grip and drag.','Check bottoming at race fuel and the fastest compression.',wet&&!wb);
 add('packers','Aero & platform','Packers / bump-stop clearance','Keep baseline','Travel limits must match spring rate, fuel and ride height.','More packers may cause earlier bump-stop contact.','Measure suspension travel before changing.',false,true);
 add('farb','Suspension','Front anti-roll bar',wet&&!wb||s.balance==='responsive'?'Test 1 step softer':'Keep baseline','Softer front roll stiffness can improve slow/medium-corner grip.','Too soft can reduce response and platform control.','Compare turn-in and steady-state balance.',wet&&!wb||s.balance==='responsive');
 add('rarb','Suspension','Rear anti-roll bar',wet&&!wb||stable?'Test 1 step softer':'Keep baseline','Softer rear roll stiffness can improve traction.','It may add understeer.','Check exits and changes of direction.',wet&&!wb||stable);
 for(const axle of ['Front','Rear'])add(axle==='Front'?'fspring':'rspring','Suspension',`${axle} springs`,'Keep baseline',proto?'Preserve aero-platform control.':'Match compliance to loaded clearance.','Softer springs can cause bottoming.','Only soften for poor compliance after checking travel.');
 add('heave','Suspension','Third spring / heave','Keep baseline','Supports the aero platform where fitted.','Changes dive, clearance and high-speed balance.','Use measured travel and exposed controls.',false,true);
 for(const axle of ['Front','Rear'])for(const speed of ['Slow','Fast'])for(const type of ['bump','rebound'])add(`${axle[0]}${speed[0]}${type[0]}`,'Dampers',`${axle} ${speed.toLowerCase()} ${type}`,'Keep baseline',speed==='Slow'?'Controls body movement during braking, steering and throttle transitions.':'Controls rapid suspension movement, including kerbs.','Effects depend on springs, available travel and corner phase.',speed==='Fast'&&track.bumps===3?'For kerb skipping, check bottoming, then test one softer bump step.':'Change only after a repeatable handling problem.');
 for(const axle of ['Front','Rear']){add(`${axle[0]}camber`,'Alignment',`${axle} camber`,'Keep baseline','Choose camber using tyre temperatures and braking/cornering balance.','Extra negative camber can cost straight-line contact and change wear.','Compare inner/middle/outer temperatures under equal conditions.');add(`${axle[0]}toe`,'Alignment',`${axle} toe`,'Keep baseline','Toe changes response, stability, drag and tyre scrub.','Less scrub can reduce stability.','Use one small step after checking temperature and handling.');}
 add('caster','Alignment','Caster','Keep baseline','The adjustment may be restricted or fixed.','Changes steering feel and dynamic camber.','Check the actual garage range.',false,true);
 add('bias','Brakes','Brake bias',wet&&!wb?'Test +0.4 percentage points front':stable?'Test +0.2 percentage points front':'Keep baseline; tune in 0.2-point steps','Tune around this car and selected brake map. There is no universal front percentage.','More front bias can reduce rotation and overload the fronts.','Rear unstable while braking: move forward. Front limited: cautiously test rearward.',wet&&!wb||stable);
 add('pressure','Brakes','Maximum brake pressure',!car.abs&&wet&&!wb?'Test 1 step less pressure':'Keep baseline','Use your calibrated pedal range without sustained locking.','Lower pressure can reduce maximum deceleration.','Check pedal calibration and braking trace first.',!car.abs&&wet&&!wb);
 for(const axle of ['Front','Rear'])add(`${axle[0]}duct`,'Brakes',`${axle} brake ducts`,num(s.trackTemp,30)>40||num(s.air,20)>30||track.brakes===3?'Check temperature; open if needed':'Keep baseline','Select cooling with temperatures over a representative stint.','Closing ducts may reduce drag but can overheat brakes.','Open one step if too hot. Do not close solely because it is qualifying.');
 add('pads','Brakes','Brake pads / disc options','Keep permitted baseline','Available compounds and ranges depend on car and game version.','Wear, temperature window and bite can change.','Test stopping consistency and wear over your planned stint.',false,true);
 if(car.abs)add('abs','Electronics','ABS map','Keep familiar map','LMGT3 map numbers are not a universal intervention-strength scale.','Changing the map may change the ideal bias.','Choose the map first; then fine-tune brake bias.');
 add('tc','Electronics','Traction control',wet&&!wb?'Test more intervention, 1 step':'Keep baseline','Aim for clean exits with limited persistent power cuts.','Too much intervention can hurt acceleration.','Confirm the adjustment direction in the game tooltip.',wet&&!wb);
 for(const [id,name]of[['tcslip','TC slip target'],['tccut','TC power cut']])add(id,'Electronics',name,'Keep baseline','Slip and cut controls interact.','Large changes can make exits inconsistent.','Change one control at a time; check the tooltip direction.',false,true);
 if(car.cls==='Hypercar')add('migration','Brakes','Brake migration','Keep baseline','Balance may move dynamically on cars exposing this control.','Incorrect migration may destabilise brake release.','Tune with braking traces; skip if unavailable.',false,true);
 add('preload','Differential & drive','Differential preload','Keep baseline','Tune using the corner phase where the problem occurs.','Less preload can add rotation but reduce stability.','For slow entry understeer, test one step lower and recheck the rear.',false,true);
 for(const part of ['Power','Coast'])add(part.toLowerCase(),'Differential & drive',`${part} locking / ramp`,'Keep baseline','Ramp angle and locking percentage can have opposite numeric directions.','Changes may improve one phase and worsen another.','Read the tooltip and change one exposed control.',false,true);
 add('gears','Differential & drive','Gear ratios / final drive','Use permitted track gear set','Check top gear at the longest straight, including a tow.','Longer gearing may reduce acceleration.','Avoid hitting the limiter before the braking zone.',false,true);
 add('compound','Tyres','Tyre compound',s.tyreCompound!=='auto'?`Your choice: ${s.tyreCompound}`:wet?'Wet tyres':s.weather==='dry'?'Slick tyres':'Choose from grip on the racing line','Damp and changing conditions require a crossover check on track.','Wet tyres can overheat on a drying line.','Check remaining rain, standing water and tread temperature.',true);
 for(const corner of ['Front left','Front right','Rear left','Rear right'])add(`p${corner.split(' ').map(x=>x[0]).join('')}`,'Tyres',`${corner} cold pressure`,'Start at legal baseline','Cold settings depend on measured hot pressure and temperatures. No universal target is assumed.','Too high or low can hurt contact, wear and temperature.','Record hot pressure after representative laps; change one small step.');
 add('tyreplan','Tyres','Tyre management',s.session==='quali'?'Warm up progressively; prepare flying laps':s.tyreAge==='used'?'Check existing wear before extending stint':'Check wear across the planned stint','Tyres need repeatable preparation for a fair setup comparison.','Sliding and repeated lockups increase wear.','Log age, hot pressure and temperature with the run.');
 add('fuel','Fuel & power','Starting fuel',`${f.startFuel.toFixed(1)} L · ${f.measured?'measured inputs':'provisional'}`,'Includes your run, formation/out-laps and reserve. Tank and manual load can limit it.','More fuel adds weight. A low load may require a stop.','Confirm fuel use on track; inspect the Stints page.',true);
 add('cooling','Fuel & power','Engine radiator / cooling','Keep baseline; check full-stint temperatures','Ambient temperature, traffic and engine load change cooling needs.','Less cooling may reduce drag but risks overheating.','Open one step if temperatures exceed the game’s safe range.',false,true);
 add('engine','Fuel & power','Engine / fuel map','Use permitted performance map','Fuel-saving maps trade lap time against stint length.','A different map changes consumption and invalidates the fuel estimate.','Measure again after changing the map.',false,true);
 if(car.hybrid)add('hybrid','Fuel & power','Hybrid / regeneration map','Keep car-specific baseline','Deployment and regeneration differ between hybrid systems.','Changes may affect braking and energy use.','Use only exposed settings and verify over a full lap.',false,true);
 if(car.ve)add('energy','Fuel & power','Virtual energy',f.veUse?`${f.veLaps} racing laps at starting energy`:'Enter measured use in Advanced','Fuel litres and virtual energy can impose different stint limits.','Fuel-only planning may miss an energy-limited stop.','Record percentage used per racing lap; check the race rules.');
 if(s.rules==='fixed')for(const row of rows)if(!['fuel','bias','tc','abs','tyreplan','energy','compound'].includes(row.id)){row.value='Use event’s locked value';row.changed=false;row.why='This event is marked as fixed setup. Change only what the game permits.';}
 const notes=['Load the in-game baseline for this car and circuit first. These are conservative test directions, not verified complete numeric setups.','Use the value and range displayed in your garage. Skip settings this car or event does not expose.'];
 if(s.grip==='low')notes.push('Low track grip: build tyre temperature before judging balance.');if(s.wind!=='calm')notes.push('Wind can change high-speed balance and top speed. Repeat tests in similar conditions.');if(['drying','worsening','damp'].includes(s.weather))notes.push('Changing conditions: evaluate the racing line before switching tyres; there is no guaranteed crossover lap.');if(car.rearEngine)notes.push('Keep fuel and tyre state consistent when assessing the rear-engined Porsche.');if(track.estimated)notes.push('This layout distance is approximate. Measured lap time and fuel use override distance-based estimates.');if(track.recent)notes.push('This circuit was recently announced. Confirm availability and layout in your installed game.');
 return{rows,notes,car,track,s,fuel:f};
}
export const SYMPTOMS=[['entry_under','Won’t turn under braking'],['entry_over','Rear slides under braking'],['mid_under','Runs wide mid-corner'],['mid_over','Rear slides mid-corner'],['exit_under','Runs wide on throttle'],['exit_over','Wheelspin / loose on exit'],['kerbs','Skips over kerbs'],['bottoming','Bottoms out'],['front_lock','Front wheels lock'],['rear_lock','Rear wheels lock'],['hot_tyres','Tyres overheat'],['slow_straight','Too slow on straights']];
export function diagnose(input,symptom,speed='medium'){const {car,s}=context(input),fast=speed==='high';let r={id:'farb',action:'Test 1 step softer front anti-roll bar',reason:'May improve front grip.',check:'Repeat the same corner with equal fuel and tyre state.'};
 const map={entry_under:['bias','Test brake bias 0.2 percentage points rearward','A small move may reduce front braking saturation. Stop if the rear becomes unstable.'],entry_over:['bias','Test brake bias 0.2 percentage points forward','May reduce rear braking instability; also check downshift timing.'],mid_under:['farb','Test 1 step softer front anti-roll bar','May increase front grip in steady cornering.'],mid_over:['rarb','Test 1 step softer rear anti-roll bar','May increase rear grip, with some understeer trade-off.'],exit_under:['preload','Check differential power locking before changing','Separate throttle-induced push from entry speed; numeric direction depends on the control.'],exit_over:['tc','Test one step more TC intervention','May reduce wheelspin; compare acceleration and power cuts.'],kerbs:['FFb','Test 1 step softer front fast bump','Check bottoming and line choice first; then test kerb compliance.'],bottoming:['frontheight','Test 1 step higher ride height at both axles','Retain rake initially and check clearance at race fuel.'],front_lock:['bias','Test brake bias 0.2 percentage points rearward','Verify pedal calibration, ABS map if fitted, and tyre state first.'],rear_lock:['bias','Test brake bias 0.2 percentage points forward','May reduce rear locking; check downshift timing too.'],hot_tyres:['tyreplan','Reduce sliding, then compare tyre temperatures','Check hot pressures and driving before changing alignment.'],slow_straight:['wing','Test 1 step less rear wing','Check exits, tow, damage, fuel load and power map first.']};
 const v=map[symptom];if(!v)throw Error('Choose a handling problem.');r={...r,id:v[0],action:v[1],reason:v[2]};if(fast&&symptom==='mid_over'&&!car.wingless)r={...r,id:'wing',action:'Test 1 step more rear wing',reason:'High-speed rear instability may respond to a rearward aero balance.'};if(fast&&symptom==='mid_under')r={...r,id:'frontaero',action:'Check aero balance and loaded ride heights',reason:'High-speed understeer may be platform-related; avoid blindly changing roll stiffness.'};if(car.wingless&&r.id==='wing')r={...r,id:'rearheight',action:'Keep aero baseline; check drag, power and exits',reason:'The original Peugeot has no conventional rear wing.'};if(s.rules==='fixed'&&!['tc','bias','tyreplan'].includes(r.id))r={...r,id:'tyreplan',action:'Keep locked setup; test driving line and tyre preparation',reason:'The event is marked as fixed setup.'};return r;
}
