import {normalise} from './engine.js';
export const combo=s=>[s.car,s.track,s.weather,s.session,s.variant,s.car==='custom'?s.customName:'',s.track==='custom'?s.customTrack:''].join('|');
export const blank=()=>({schema:1,config:normalise(),tab:'session',saved:[],runs:[],tests:[],values:{},current:{},checks:{},overrides:{},sessionLengths:{race:{length:20,unit:'minutes'},quali:{length:10,unit:'minutes'},practice:{length:20,unit:'minutes'}}});
const text=(v,max=500)=>typeof v==='string'?v.slice(0,max):'';
const cleanMap=(m,boolean=false)=>{const r={};if(!m||typeof m!=='object'||Array.isArray(m))return r;for(const [k,v]of Object.entries(m).slice(0,15000))if(k.includes('|')&&k.length<600&&k!=='__proto__')r[k]=boolean?!!v:text(v);return r;};
export function sanitise(raw){if(!raw||raw.schema!==1||!raw.config)throw Error('This is not an Apex Garage backup.');const s=blank();s.config=normalise(raw.config);s.tab=['session','setup','stints','improve','saved'].includes(raw.tab)?raw.tab:'session';for(const k of ['values','current','overrides','checks'])s[k]=cleanMap(raw[k],k==='checks');for(const k of ['race','quali','practice']){const c=normalise(raw.sessionLengths?.[k]);if(raw.sessionLengths?.[k])s.sessionLengths[k]={length:c.length,unit:c.unit};}
 s.saved=(Array.isArray(raw.saved)?raw.saved:[]).slice(0,200).filter(r=>r&&typeof r==='object').map(r=>({id:text(r.id,100),name:text(r.name,100)||'Saved setup',date:text(r.date,50),notes:text(r.notes,3000),config:normalise(r.config),values:cleanMap(r.values),current:cleanMap(r.current),overrides:cleanMap(r.overrides),checks:cleanMap(r.checks,true)}));
 s.runs=(Array.isArray(raw.runs)?raw.runs:[]).slice(0,500).filter(r=>r&&typeof r==='object').map(r=>({id:text(r.id,100),date:text(r.date,50),config:normalise(r.config),best:validNum(r.best),average:validNum(r.average),fuel:validNum(r.fuel),laps:validNum(r.laps),change:text(r.change),notes:text(r.notes,3000)}));
 s.tests=(Array.isArray(raw.tests)?raw.tests:[]).slice(0,500).filter(r=>r&&typeof r==='object').map(r=>({id:text(r.id,100),date:text(r.date,50),combo:text(r.combo,600),setting:text(r.setting,100),action:text(r.action),previous:text(r.previous),previousChosen:text(r.previousChosen),outcome:['pending','better','same','worse','undone'].includes(r.outcome)?r.outcome:'same',undone:!!r.undone}));return s;}
const validNum=v=>v!==null&&v!==''&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null;
export function sliceMaps(state,config=state.config){const prefix=combo(config)+'|',result={};for(const k of ['values','current','checks','overrides'])result[k]=Object.fromEntries(Object.entries(state[k]).filter(([key])=>key.startsWith(prefix)));return result;}
export function loadSaved(state,record){state.config=normalise(record.config);const prefix=combo(state.config)+'|';for(const k of ['values','current','checks','overrides']){for(const key of Object.keys(state[k]))if(key.startsWith(prefix))delete state[k][key];Object.assign(state[k],record[k]||{});}return state;}
export function applyTest(state,record){if(state.tests.some(t=>t.combo===combo(state.config)&&t.outcome==='pending'&&!t.undone))throw Error('Finish or undo your current test first.');const key=combo(state.config)+'|'+record.setting;const t={...record,combo:combo(state.config),previous:state.overrides[key]||'',previousChosen:state.values[key]||'',outcome:'pending',undone:false};state.overrides[key]=record.action;delete state.values[key];state.tests.unshift(t);state.tests=state.tests.slice(0,500);return t;}
export function undoTest(state,id){const t=state.tests.find(t=>t.id===id);if(!t||t.undone)throw Error('This test has already been undone.');const newer=state.tests.slice(0,state.tests.indexOf(t)).some(x=>x.combo===t.combo&&x.setting===t.setting&&!x.undone);const key=t.combo+'|'+t.setting;if(newer||state.overrides[key]!==t.action)throw Error('Undo the newer change to this setting first.');if(t.previous)state.overrides[key]=t.previous;else delete state.overrides[key];if(t.previousChosen)state.values[key]=t.previousChosen;else delete state.values[key];t.undone=true;t.outcome='undone';return t;}
export function comparable(a,b){const x=a.config,y=b.config;if(!x||!y)return false;return x.car===y.car&&x.track===y.track&&x.weather===y.weather&&x.variant===y.variant&&x.tyreAge===y.tyreAge&&x.tyreCompound===y.tyreCompound&&x.grip===y.grip&&x.wind===y.wind&&Math.abs(Number(x.trackTemp)-Number(y.trackTemp))<=5&&Math.abs(Number(x.air)-Number(y.air))<=5&&a.fuel!==null&&b.fuel!==null&&Math.abs(a.fuel-b.fuel)<=5;}
